theme: minima
title: NeuroExo
#author:
#email: email goes here
description: BMI Robotic Rehabilitation 
permalink: pretty
header_pages:
  - about.md
  - research.md
  - people.md
  - publications.md
  - contact.md
gems: [jekyll-paginate-v2]
plugins: 
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
