theme: minima
title: NeuroExo
#author:
#email: email goes here
description: BMI Robotic Rehabilitation
permalink: pretty
header_pages:
  - about.md
  - research.md
  - people.md
  - publications.md
  - contact.md
show_excerpts: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate
gems:
  - jekyll-paginate
paginate: 3
paginate_path: "/page-:num/"

  
