theme: minima
title: NeuroExo
#author:
#email: email goes here
description: BMI Robotic Rehabilitation
Using noninvasive Brain Machine Interface to rehabilitate stoke victims and to improve efficiency, cost, reliability and ease of use of previous methods of rehabilitaion.
permalink: pretty
header_pages:
  - about.md
  - research.md
  - people.md
  - publications.md
  - contact.md
show_excerpts: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
paginate: 3
paginate_path: "/page-:num/"
